<?php

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\omnipedia_site_theme\Hook\BlockHooks;
use Drupal\omnipedia_site_theme\Hook\EuCookieCompliancePopUpHooks;
use Drupal\omnipedia_site_theme\Hook\HtmlHooks;
use Drupal\omnipedia_site_theme\Hook\MaintenancePageHooks;
use Drupal\omnipedia_site_theme\Hook\MediaHooks;
use Drupal\omnipedia_site_theme\Hook\OmnipediaRegionPlaceholderHooks;
use Drupal\omnipedia_site_theme\Hook\PageHooks;
use Drupal\omnipedia_site_theme\Hook\PageTitleHooks;
use Drupal\omnipedia_site_theme\Hook\RegionHooks;
use Drupal\omnipedia_site_theme\Hook\SiteBrandingBlockHooks;
use Drupal\omnipedia_site_theme\Hook\WikiSearchHooks;

/**
 * Implements \hook_theme().
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_theme(
  array $existing, string $type, string $theme, string $path,
): array {

  return \Drupal::classResolver(OmnipediaRegionPlaceholderHooks::class)->theme(
    $existing, $type, $theme, $path
  );

}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_theme_suggestions_html_alter(
  array &$suggestions, array $variables
): void {

  \Drupal::classResolver(HtmlHooks::class)->themeSuggestionsHtmlAlter(
    $suggestions, $variables,
  );

}

/**
 * Prepares variables for HTML document templates.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_html(array &$variables): void {

  \Drupal::classResolver(HtmlHooks::class)->preprocessHtml($variables);

}

/**
 * Prepares variables for the page template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_page(array &$variables): void {

  \Drupal::classResolver(PageHooks::class)->preprocessPage($variables);

}

/**
 * Prepares variables for the maintenance page template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_maintenance_page(
  array &$variables,
): void {

  \Drupal::classResolver(
    MaintenancePageHooks::class,
  )->preprocessMaintenancePage($variables);

}

/**
 * Prepares variables for the first sidebar region template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_region__sidebar_first(
  array &$variables,
): void {

  \Drupal::classResolver(RegionHooks::class)->attachLibrariesToSidebars(
    $variables,
  );

}

/**
 * Prepares variables for the second sidebar region template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_region__sidebar_second(
  array &$variables,
): void {

  \Drupal::classResolver(RegionHooks::class)->attachLibrariesToSidebars(
    $variables,
  );

}

/**
 * Prepares variables for Omnipedia region placeholder templates.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_omnipedia_region_placeholder(
  array &$variables,
): void {

  \Drupal::classResolver(
    OmnipediaRegionPlaceholderHooks::class,
  )->preprocessRegionPlaceholder($variables);

}

/**
 * Implements hook_element_info_alter().
 *
 * This attaches the 'omnipedia_site_theme/form_radios' library to the 'radios'
 * element.
 */
function omnipedia_site_theme_element_info_alter(array &$info): void {
  $info['radios']['#attached']['library'][] =
    'omnipedia_site_theme/form_radios';
}

/**
 * Implements hook_form_FORM_ID_alter.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_form_views_exposed_form_alter(
  array &$form, FormStateInterface $formState, string $formId,
): void {

  \Drupal::classResolver(WikiSearchHooks::class)->alterViewsExposedForm(
    $form, $formState, $formId,
  );

}

/**
 * Prepares variables for the 'help_block' block template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_block__help_block(
  array &$variables,
): void {

  \Drupal::classResolver(BlockHooks::class)->attachLibrariesToHelpBlock(
    $variables,
  );

}

/**
 * Prepares variables for the 'omnipedia_current_date' block template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_block__omnipedia_current_date(
  array &$variables,
): void {

  \Drupal::classResolver(BlockHooks::class)->attachLibrariesToCurrentDateBlock(
    $variables,
  );

}

/**
 * Prepares variables for the 'omnipedia_join' block template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_block__omnipedia_join(
  array &$variables,
): void {

  \Drupal::classResolver(BlockHooks::class)->attachLibrariesToJoinBlock(
    $variables,
  );

}

/**
 * Prepares variables for the 'omnipedia_page_revision_history' block template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_block__omnipedia_page_revision_history(
  array &$variables
): void {

  \Drupal::classResolver(
    BlockHooks::class,
  )->attachLibrariesToPageRevisionHistoryBlock($variables);

}

/**
 * Prepares variables for the 'system_branding_block' block template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_block__system_branding_block(
  array &$variables
): void {

  \Drupal::classResolver(SiteBrandingBlockHooks::class)->preprocess($variables);

}

/**
 * Prepares variables for media entities.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_media(array &$variables): void {

  \Drupal::classResolver(MediaHooks::class)->preprocessMedia($variables);

}

/**
 * Prepares variables for image media entities.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_media__image(
  array &$variables,
): void {

  \Drupal::classResolver(
    MediaHooks::class,
  )->revertImageMediaImageCaptionFormatter($variables);

}

/**
 * Prepares variables for menu templates.
 *
 * This enables RefreshLess lazy link preloading for the 'main' and 'footer'
 * menus.
 */
function omnipedia_site_theme_preprocess_menu(array &$variables): void {

  if (\in_array($variables['menu_name'], ['main', 'footer']) === false) {
    return;
  }

  $variables['attributes']['data-refreshless-lazy-preload'] = true;

}

/**
 * Prepares variables for node templates.
 *
 * Opt nodes into RefreshLess lazy link preloading.
 */
function omnipedia_site_theme_preprocess_node(array &$variables): void {

  $variables['attributes']['data-refreshless-lazy-preload'] = true;

}

/**
 * Prepares variables for the omnipedia-header.html.twig template.
 *
 * This adds a 'button-placeholder' class to the 'menu_link' element.
 *
 * This attaches the 'omnipedia_site_theme/header' library to this template.
 *
 * @see \Drupal\omnipedia_block\Plugin\Block\Header
 *   Used by this block.
 */
function omnipedia_site_theme_preprocess_omnipedia_header(
  array &$variables
): void {

  $variables['menu_link']['#attributes']['class'][] = 'button-placeholder';

  $variables['#attached']['library'][] = 'omnipedia_site_theme/header';

}

/**
 * Prepares variables for page title templates.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_page_title(array &$variables): void {

  \Drupal::classResolver(PageTitleHooks::class)->attachLibraries($variables);

}

/**
 * Prepares variables for the eu_cookie_compliance_popup_info template.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_eu_cookie_compliance_popup_info(
  array &$variables,
): void {

  \Drupal::classResolver(
    EuCookieCompliancePopUpHooks::class
  )->preprocessPopUpInfo($variables);

}

/**
 * Prepares variables for views exposed form templates.
 */
// @phpstan-ignore-next-line
#[LegacyHook]
function omnipedia_site_theme_preprocess_views_exposed_form(
  array &$variables,
): void {

  \Drupal::classResolver(WikiSearchHooks::class)->preprocessViewsExposedForm(
    $variables,
  );

}
